Openfam2.0
OpenFAM/OpenFAM.github.io pull request #1
Opened 2021-02-24 06:17 UTC by faizan-barmawer

OpenFAM 2.0 documentation update:

     - Updated all man-page files for exception and c++ convention changes
     - Added man pages for fam_barrier_all and fam_stat APIs
     - Added pages for services and configuration files description
     - Updated index page with OpenFAM release information
     - Modification to OpenFAM 1.0 documentation include:
       - Added description and usage for fam_global descriptor in create_region
         and allocate data item man pages.
       - Added a note on usage of fam_quiet for all non-fetch atomic api man pages.
       - Added man-page for fam_size API
       - Corrected few spelling mistakes.

These changes are published from my private repository and can be viewed from this link:

https://faizan-barmawer.github.io/OpenFAM.github.io/

2021-02-24 08:22 UTC, mashoodk requested changes

2021-02-24 08:22 UTC, mashoodk commented on errors.html
> +			<p>The OpenFAM 2.0 implementation define a fam exception class, which
```suggestion
			<p>The OpenFAM 2.0 implementation defines a fam exception class, which
```

2021-02-24 08:22 UTC, mashoodk commented on errors.html
> +        // FAM_ERR_TIMEOUT, FAM_ERR_OUTOFRANGE, FAM_ERR_NOPERM
extra spacing ?

2021-02-24 08:22 UTC, mashoodk commented on fam_copy.html
> +	<p>Copy data item from one FAM-resident data item to another FAM-resident data item within a different or same region.</p>
within a same region or across different regions

2021-02-24 08:22 UTC, mashoodk commented on fam_stat.html
> +		fam_stat(arrayDescriptor, info);
missing , myFam->  ?

2021-02-24 20:37 UTC, ssinghal53 commented
Please separate release notes into a separate file from index.html

2021-02-25 01:26 UTC, ssinghal53 commented on fam_barrier_all.html
> +	<h2>Example</h2>
Unclear what this means. I believe you're saying that fam_barrier_all() should be preceded by a fam_quiet() to ensure that pending operations are completed before the barrier is reached.

2021-02-25 01:30 UTC, ssinghal53 commented on services.html
> +</ul>
Rephrase the above. Poor language style.

2021-02-25 01:31 UTC, ssinghal53 commented on services.html
> +As shown in Figure 1, PE will make an RPC call to CIS, in-turn CIS will make an RPC call to metadata
Figure 1 does not show any RPC calls being made. Again No future tense for completed work.

2021-02-25 01:32 UTC, ssinghal53 commented on services.html
> +other services. Figure 2, shows one such configuration where CIS and metadata running as a single service,
Same as before. Fig. 2 does not show any RPC calls. Please clean out all language in this file.

2021-02-25 03:58 UTC, ssinghal53 commented on fam_initialize.html
>  	memset((void *)fm, 0, sizeof(Fam_Options));
What does the user need to do to pick only some options to be default? The description above seems to be an "all or nothing" behavior.

2021-02-25 04:22 UTC, ssinghal53 commented on fam_get_option.html
> +	The following option names are available:
VERSION below is returning "0.0.1". This default is incorrect-- should match the version of the OpenFAM library

2021-02-25 04:35 UTC, ssinghal53 commented on fam_stat.html
> +} Fam_Stat;
Add comments or text to describe the fields in the FAM_Stat structure. What is Fam_Stat.key?

2021-02-25 10:37 UTC, clarete-riana commented on index.html
> +		<p>We are pleased to announce the release of OpenFAM 2.0 reference implementation. The highlights of the release is summarized below.
The highlights of the release are*

2021-02-25 10:37 UTC, clarete-riana commented on index.html
> +		Please refer NEWS.md for list of features, enhancements and bug fixes that are added to the source tree in all the released versions.
You may have to specify where NEWS.md can be found.

2021-02-25 10:37 UTC, clarete-riana commented on index.html
> +		Please refer NEWS.md for list of features, enhancements and bug fixes that are added to the source tree in all the released versions.
Also these two lines can be added as notes after the feature description for better continuity in the description.

2021-02-25 10:37 UTC, clarete-riana commented on index.html
> +			<li>Scalability improvements: Support for larger pool of memory by scaling to multiple memory servers. See <a href="services.html">services</a> for more details. </li>
Multiple memory server support and hence support for larger pools of memory spanning across memory servers.

2021-02-25 10:37 UTC, clarete-riana commented on index.html
> +					<li>NVMM background worker thread is disabled from memory service.</li>
Looks like a NVMM change... Does it make sense to describe here?

2021-02-25 10:37 UTC, clarete-riana commented on index.html
> +					<li>Delayed Free: Zeroing of memory have been moved from allocation path to free path by using delayed free thread.</li>
Zeroing of memory has* been moved...

2021-02-25 10:37 UTC, clarete-riana commented on index.html
> +					<li>Delayed Free: Zeroing of memory have been moved from allocation path to free path by using delayed free thread.</li>
You may need to bring out how this will help... example say Zeroing of memory has been moved from performance sensitive allocation path to free path....

2021-02-25 10:37 UTC, clarete-riana commented on index.html
> +					<li>Modified fam_copy API to copy data between different regions.</li>
Is this enhancement to the existing capability of fam_copy or modification to its existing behavior? I think it is the first, and it needs to come out from the description.

2021-02-25 10:37 UTC, clarete-riana commented on errors.html
>  				member functions, <code>fam_error()</code> and <code>fam_error_msg()/what()</code> and take
there is no need for , here after member functions.

2021-02-25 10:37 UTC, clarete-riana commented on errors.html
> +				numbers to categorize various types of failures, like <code>Runtime</code>, <code>Allocator</code>,
No need for , after failures

2021-02-25 10:37 UTC, clarete-riana commented on errors.html
> +				error condition. The fam exception object received by the caller in case of an
The fam exception object received by the caller, in case of an error, will contain...

2021-02-25 10:37 UTC, clarete-riana commented on errors.html
> +			<p>The OpenFAM 2.0 implementation define a fam exception class, which
Fam_Exception  class ( for consistency)

2021-02-25 10:37 UTC, clarete-riana commented on errors.html
> +				<code>fam_put_blocking()</code> will either complete successfully, or throw Fam_Exception object
Fam_Exception object is returned or thrown?

2021-02-25 10:37 UTC, clarete-riana commented on services.html
> + As expected, the memory server becomes a bottleneck even for a small number of concurrent PEs.
The memory server soon becomes a bottleneck with the increase in number of concurrent PEs.

2021-02-25 10:37 UTC, clarete-riana commented on services.html
> +Yaml based configuration parameters are available to decide how these services are running.  If the components are running as separate services,
available to define* how these servcies..

2021-02-25 10:37 UTC, clarete-riana commented on services.html
> +We have defined an RPC path and a direct path for all the three components – CIS, memory management service and metadata management service.
We have defined a* RPC path and a direct path for interactions between the three components...

2021-02-25 10:37 UTC, clarete-riana commented on services.html
> +a grpc call is made to the service. If the services are running within other component (direct path), a function call is made.
If components/services are collocated within the same node, they interact through direct function calls.

2021-02-25 10:37 UTC, clarete-riana commented on services.html
> +If all the components are running as separate services, a grpc call will be made to the services.
Throughout this description the concept of separate service is confusing to me. so even if the services are running on the same node we are making GPRC calls? That can be avoided right? Unless there are other reasons fro doing this. We need to think through this design a bit more...

2021-02-25 10:37 UTC, clarete-riana commented on services.html
> +<p> Now let us look at some of the possible combinations.
Below are some of the possible combinations:

2021-02-25 10:37 UTC, clarete-riana commented on services.html
> +In this case PE will make a grpc call to CIS and CIS makes direct  function call to
function calls*

2021-02-25 10:37 UTC, clarete-riana commented on services.html
> +<p>See configuration and startup of OpenFAM 2.0 services in this section. <a href="config_files.html">Configuration Files</a></p>
The ". " should be after Configuration Files.

2021-03-01 19:44 UTC, ssinghal53 commented on fam_create_region.html
> +	<p>Fam_Region_Descriptor provides a method to retrieve an opaque read-only data structure called
insert <code></code> around "Fam_Region_Descriptor" on line 170.

2021-03-01 19:47 UTC, ssinghal53 commented on fam_create_region.html
> +	<p>Fam_Region_Descriptor can be instantiated from Fam_Global_Descriptor using the following constructor.</p>
Line 178, insert code /code blocks around Fam_Region_Descriptor/Fam_Global_Descriptor for consistent formatting.

2021-03-01 19:51 UTC, ssinghal53 commented on fam_allocate.html
> +	<p><code>Fam_Descriptor</code> provides a method to retrieve an opaque read-only data structure called
Line 142 (Notes) add code /code block around fam_lookup()

2021-03-01 19:55 UTC, ssinghal53 commented on fam_change_permissions.html
> -		<p>Copyright 2019, Hewlett Packard Enterprise Development Co, LLP</p>
Line 132, Notes should say that permissions are checked on first descriptor use in a running program. Changed permissions are only applied the next time the program is run, not immediately on next access.

2021-03-01 19:58 UTC, ssinghal53 commented on fam_change_permissions.html
> +		<p>Copyright 2021, Hewlett Packard Enterprise Development Co, LLP</p>
Delete three lines starting at 159 (// free allocated space in FAM) in this example. If the fam is deallocated, the change in permissions is meaningless for the next program.

2021-03-02 11:00 UTC, faizan-barmawer commented
Hi Sharad,

I have addressed your recent comments and updated this PR.

    - Added <code></code> block around API/descriptor names to have consistent formatting style.
    - As suggested, added a note in fam_change_permission man page.

Regards,
Faizan

2021-03-17 06:38 UTC, mashoodk approved these changes

2021-03-17 06:38 UTC, mashoodk commented on fam_allocate.html
> +						used.<span style="color:red;font-weight:bold">Is this true? <code>fam_initialize</code> says that default region name is not used. Do we still have a default region?</span></td></tr>
@faizan-barmawer we do not have default region name. We can remove this sentence.

2021-03-19 03:49 UTC, merged